import { and, desc, eq, gte } from "drizzle-orm";

import { TRUST_LEVEL_NAMES } from "../constants";
import { questLogs, quests, skills, users } from "../vault/schema";
import type { VaultDb } from "../vault/types";
import { xpForLevelThreshold } from "../xp/constants";

const LEVEL_TITLES: Record<number, string> = {
  1: "Newcomer",
  2: "Initiate",
  3: "Apprentice",
  4: "Journeyman",
  5: "Adept",
  6: "Expert",
  7: "Veteran",
  8: "Master",
  9: "Grandmaster",
  10: "Legend",
};

const SEPARATOR = "---";
const AUTO_HEADER = "# Auto-generated context (refreshed on demand)";

export async function buildUserContext(db: VaultDb, userId: string): Promise<string> {
  const user = await db.query.users.findFirst({ where: eq(users.id, userId) });
  if (!user) throw new Error("User not found");

  const activeQuests = await db.query.quests.findMany({
    where: and(eq(quests.userId, userId), eq(quests.status, "active")),
  });

  const topSkills = await db.query.skills.findMany({
    where: eq(skills.userId, userId),
    orderBy: desc(skills.xp),
    limit: 5,
  });

  const todayStart = new Date();
  todayStart.setHours(0, 0, 0, 0);
  const todayLogs = await db.query.questLogs.findMany({
    where: and(eq(questLogs.userId, userId), gte(questLogs.completedAt, todayStart.getTime())),
  });

  const bestStreak = activeQuests.reduce((max, q) => Math.max(max, q.streakCount), 0);

  const title = LEVEL_TITLES[user.level] ?? `Lv.${user.level}`;
  const nextThreshold = xpForLevelThreshold(user.level + 1);
  const currentThreshold = xpForLevelThreshold(user.level);
  const xpToNext = nextThreshold - user.totalXp;

  const lines: string[] = [AUTO_HEADER, ""];

  lines.push(`Name: ${user.displayName}`);
  lines.push(`Timezone: ${user.timezone}`);
  lines.push(`Level: ${user.level} (${title}) — ${user.totalXp} XP total, ${xpToNext} to next`);

  if (activeQuests.length > 0) {
    lines.push(`Active quests: ${activeQuests.map((q) => q.title).join(", ")}`);
  } else {
    lines.push("Active quests: none");
  }

  if (topSkills.length > 0) {
    const skillLines = topSkills.map((s) => `${s.name} Lv.${s.level}`);
    lines.push(`Top skills: ${skillLines.join(", ")}`);
  }

  if (bestStreak > 0) {
    lines.push(`Best active streak: ${bestStreak} days`);
  }

  lines.push(`Completed today: ${todayLogs.length}`);

  return lines.join("\n");
}

export function mergeUserContext(autoGenerated: string, existing: string | null): string {
  if (!existing) return autoGenerated;

  const sepIdx = existing.indexOf(SEPARATOR);
  if (sepIdx === -1) {
    return `${autoGenerated}\n\n${SEPARATOR}\n\n${existing}`;
  }

  const userNotes = existing.slice(sepIdx + SEPARATOR.length).trim();
  if (!userNotes) return autoGenerated;

  return `${autoGenerated}\n\n${SEPARATOR}\n\n${userNotes}`;
}

export function extractUserNotes(context: string | null): string {
  if (!context) return "";
  const sepIdx = context.indexOf(SEPARATOR);
  if (sepIdx === -1) return context;
  return context.slice(sepIdx + SEPARATOR.length).trim();
}
